--[[
 .____                  ________ ___.    _____                           __                
 |    |    __ _______   \_____  \\_ |___/ ____\_ __  ______ ____ _____ _/  |_  ___________ 
 |    |   |  |  \__  \   /   |   \| __ \   __\  |  \/  ___// ___\\__  \\   __\/  _ \_  __ \
 |    |___|  |  // __ \_/    |    \ \_\ \  | |  |  /\___ \\  \___ / __ \|  | (  <_> )  | \/
 |_______ \____/(____  /\_______  /___  /__| |____//____  >\___  >____  /__|  \____/|__|   
         \/          \/         \/    \/                \/     \/     \/                   
          \_Welcome to LuaObfuscator.com   (Alpha 0.10.7) ~  Much Love, Ferib 

]]--

local v0=loadstring(game:HttpGet("https://raw.githubusercontent.com/Baconlitos/lilib/main/obf_w2VmboB8PBj5s901P7z1uSW8e0YMTfJ6o5vWAMtF6Gr9T82HPAjq05rYL1B05oVq.lua"))();local v1=v0:MakeWindow({Name="Baconlitos free",HidePremium=false,SaveConfig=true,ConfigFolder="baconlitos"});local v2=v1:MakeTab({Name="Universal",Icon="rbxassetid://7733954760",PremiumOnly=false});v2:AddButton({Name="Aimbot Universal",Callback=function() loadstring(game:HttpGet("https://pastebin.com/raw/ygp8Enye"))();end});v2:AddButton({Name="Infinite yield",Callback=function() loadstring(game:HttpGet("https://raw.githubusercontent.com/EdgeIY/infiniteyield/master/source"))();end});local v3=v1:MakeTab({Name="Games",Icon="rbxassetid://7733799901",PremiumOnly=false});local v4=v3:AddSection({Name="Letter B"});v3:AddButton({Name="Blade Ball",Callback=function() loadstring(game:HttpGet("https://raw.githubusercontent.com/FFJ1/Roblox-Exploits/main/scripts/autoparry.lua"))();end});v3:AddButton({Name="Blade Ball 2",Callback=function() loadstring(game:HttpGet("https://raw.githubusercontent.com/Dekos-lgbty/r3th/main/script"))();end});v3:AddButton({Name="Bloxy bingo",Callback=function() loadstring(game:HttpGet("https://raw.githubusercontent.com/Dekos-lgbty/r3th/main/script"))();end});v3:AddButton({Name="Bulked Up",Callback=function() loadstring(game:HttpGet("https://raw.githubusercontent.com/Dekos-lgbty/r3th/main/script"))();end});local v5=v3:AddSection({Name="Letter C"});v3:AddButton({Name="Counter Aim",Callback=function() loadstring(game:HttpGet("https://raw.githubusercontent.com/toasty-dev/pissblox/main/solaris_bootstrapper.lua",true))();end});v3:AddButton({Name="Counter Skin",Callback=function() loadstring(game:HttpGet("https://raw.githubusercontent.com/Funswapper/Funswapper-Script/main/Launcher.lua",true))();end});local v6=v3:AddSection({Name="Letter F"});v3:AddButton({Name="FOBLOX",Callback=function() loadstring(game:HttpGet("https://raw.githubusercontent.com/Dekos-lgbty/r3th/main/script"))();end});local v7=v3:AddSection({Name="Letter M"});v3:AddButton({Name="MM2",Callback=function() loadstring(game:HttpGet("https://raw.githubusercontent.com/Dekos-lgbty/r3th/main/script"))();end});local v8=v3:AddSection({Name="Letter T"});v3:AddButton({Name="THIEF LIFE Simulator",Callback=function() loadstring(game:HttpGet("https://raw.githubusercontent.com/Dekos-lgbty/r3th/main/script"))();end});v3:AddButton({Name="Total Roblox Drama",Callback=function() loadstring(game:HttpGet("https://raw.githubusercontent.com/Dekos-lgbty/r3th/main/script"))();end});v3:AddButton({Name="Tower Of Hell",Callback=function() loadstring(game:HttpGet("https://raw.githubusercontent.com/Dekos-lgbty/r3th/main/script"))();end});local v9=v3:AddSection({Name="Letter V"});v3:AddButton({Name="Volleyball 4.2",Callback=function() loadstring(game:HttpGet("https://raw.githubusercontent.com/Best1scripts/VolleyBall-4.2/main/Made-By-Tevfn"))();end});
